<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.bestdata-chi</groupId>
        <artifactId>ts-oss-parent</artifactId>
        <!--        <version>1.0.0-SNAPSHOT</version>-->
        <version>1.0.1</version>
    </parent>

    <artifactId>ts-oss-api</artifactId>
    <name>ts-oss-api</name>
    <description>稳定的公共接口与数据模型（零第三方依赖）</description>

    <dependencies>
        <!-- 编译期注解处理器，不参与运行时、不向外传递（provided 不进入传递依赖） -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
